### ISSUE TITLE
Return to "Home" after 'Enjoyment'

### ISSUE THREAD

**Issue by PhilGrunewald** [PhilGrunewald/MeterApp#3] opened 2016-02-15 22:49 UTC
Is there a way to trigger 
app.showActivityList();
after clicking on 'enjoyment' screen? 
if !enjoyment app.navigateTo(x)
else app.showActivityList()?

I think that would make a good landing screen to give a sense 'this activity has been noted'.

**Comment by gozzilli** [comment] 2016-02-15 22:57
Yes, absolutely. What does enjoyment->next point to? Can it be null/done/game over?

**Comment by PhilGrunewald** [comment] 2016-03-15 13:22
All 'enjoyment' points to "next": "home"
I suggest:

"home" - the screen that lists recorded activities and the "add new" button
"activity root" - the first activity screen with Care / Work /Leisure / Food / Travel and More...
"survey root" - the first survey screen

(sorry - duplication of [issue 7](https://github.com/PhilGrunewald/MeterApp/issues/7)

**Comment by gozzilli** [comment] 2016-03-15 15:03
closing then as duplicate of issue #7

**Closed as completed by gozzilli** 2016-03-15 15:03 UTC
